public class _389_FindTheDifference {
    
    /*
    389. Find the Difference
    You are given two strings s and t.
    
    String t is generated by random shuffling string s and then add one more 
    letter at a random position.
    
    Return the letter that was added to t.
   
    Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
    
    Example 2:
    Input: s = "", t = "y"
    Output: "y"
    
    Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
     */

    public static void main(String[] args) {
        testFindTheDifference("abcd", "abcde");
        testFindTheDifference("", "y");
        testFindTheDifference("a", "aa");
        testFindTheDifference("ae", "aea");
        testFindTheDifference("ae", "eaa");
    }

    public static char findTheDifference(String s, String t) {
        
        int[] letters = new int[26];
        
        for (int i = 0; i < s.length(); i++) 
            letters[s.charAt(i) - 'a']++;
        
        for (int i = 0; i < t.length(); i++) 
            letters[t.charAt(i) - 'a']--;
        
        for (int i = 0; i < letters.length; i++) {
            if (letters[i] < 0) 
                return (char) (i + 'a');
        }
        
        return ' ';
    }

    public static void testFindTheDifference(String s, String t) {

        System.out.println("\nInput:  " + s + ", " + t);

        long start = System.nanoTime();
        char result = findTheDifference(s, t);
        long end = System.nanoTime();

        System.out.println("Output: " + result);
        System.out.println("Time: " + (end - start) + " ns");
        System.out.printf("Time: %.5f ms\n", (end - start) / 1_000_000.0);
    }
}